from django.db import models


class SimpleModel(models.Model):
    integer = models.IntegerField()
    big_integer = models.BigIntegerField()
    boolean = models.BooleanField()
    char = models.CharField(max_length=255)
    binary = models.BinaryField()
    date = models.DateField()
    date_time = models.DateTimeField()
    decimal = models.DecimalField(max_digits=10, decimal_places=2)
    duration = models.DurationField()
    email = models.EmailField()
    file = models.FileField(upload_to="test")
    file_path = models.FilePathField()
    float = models.FloatField()
    image = models.ImageField(upload_to="test")
    generic_ip = models.GenericIPAddressField()
    positive_integer = models.PositiveIntegerField()
    positive_small_integer = models.PositiveSmallIntegerField()
    slug = models.SlugField()
    small_integer = models.SmallIntegerField()
    text = models.TextField()
    time = models.TimeField()
    url = models.URLField()
    json = models.JSONField()
    uuid = models.UUIDField()
