# Generated by Django 4.2.1 on 2023-06-03 21:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SimpleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("integer", models.IntegerField()),
                ("big_integer", models.BigIntegerField()),
                ("boolean", models.BooleanField()),
                ("char", models.CharField(max_length=255)),
                ("binary", models.BinaryField()),
                ("date", models.DateField()),
                ("date_time", models.DateTimeField()),
                ("decimal", models.DecimalField(decimal_places=2, max_digits=10)),
                ("duration", models.DurationField()),
                ("email", models.EmailField(max_length=254)),
                ("file", models.FileField(upload_to="test")),
                ("file_path", models.FilePathField()),
                ("float", models.FloatField()),
                ("image", models.ImageField(upload_to="test")),
                ("generic_ip", models.GenericIPAddressField()),
                ("positive_integer", models.PositiveIntegerField()),
                ("positive_small_integer", models.PositiveSmallIntegerField()),
                ("slug", models.SlugField()),
                ("small_integer", models.SmallIntegerField()),
                ("text", models.TextField()),
                ("time", models.TimeField()),
                ("url", models.URLField()),
                ("json", models.JSONField()),
                ("uuid", models.UUIDField()),
            ],
        ),
    ]
